services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    env_file:
      - ./backend/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smart_payroll
      MYSQL_USER: payroll
      MYSQL_PASSWORD: payroll123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
