[build]
  base = "frontend"       # go into frontend folder
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.12.0"     # make sure it matches your local node
  VITE_API_URL = "https://smart-payroll-backend.onrender.com/api"  # 👈 your Render backend URL

